# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_sftpserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('key_type', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=512)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(blank=True, max_length=40, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('merge_commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_destinations', to='django_sftpserver.Commit')),
                ('parent_commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='django_sftpserver.Commit')),
            ],
        ),
        migrations.CreateModel(
            name='CommitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('key', models.CharField(blank=True, max_length=40, null=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sftpserver.Commit')),
            ],
            bases=(django_sftpserver.models.MetaFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('parent_key', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4096)),
                ('filename', models.CharField(max_length=1024)),
                ('key', models.CharField(blank=True, max_length=40, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_sftpserver.MetaFile')),
            ],
            bases=(django_sftpserver.models.MetaFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('branch', models.CharField(blank=True, max_length=256, null=True)),
                ('base_commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_sftpserver.Commit')),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='metafile',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sftpserver.Root'),
        ),
        migrations.AddField(
            model_name='commit',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_sftpserver.Root'),
        ),
        migrations.AlterUniqueTogether(
            name='root',
            unique_together=set([('name', 'branch')]),
        ),
        migrations.AlterUniqueTogether(
            name='metafile',
            unique_together=set([('root', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='commititem',
            unique_together=set([('commit', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='authorizedkey',
            unique_together=set([('user', 'name')]),
        ),
    ]
